import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Banner from "@/components/Banner/Banner";
import Newsletter from "@/components/Newsletter/Newsletter";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* BODY */}
      <body
        className={`${inter.variable} antialiased font-inter text-primary--dark-grey`}
      >
        <div className="page-wrap px-5 mx-auto max-w-screen-2xl">
          {/* HEADER */}
          <Header />
          {children}
          <Banner />
          <Newsletter />
          {/* FOOTER */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
